import type { Product, Category, Settings } from "./types";
import { completePrivacyText, completeTermsText } from "./catalog-presentation";
export const demoCategories: Category[] = [
  {
    id: "personal",
    name: "Bienestar personal",
    slug: "bienestar-personal",
    description: "Un momento que es solo tuyo.",
    image_url: "/images/product-4.webp",
    active: true,
    sort_order: 0,
  },
  {
    id: "parejas",
    name: "Para parejas",
    slug: "para-parejas",
    description: "Nuevas formas de encontrarse.",
    image_url: "/images/product-1.webp",
    active: true,
    sort_order: 1,
  },
  {
    id: "cuidado",
    name: "Cuidado íntimo",
    slug: "cuidado-intimo",
    description: "Pequeños rituales, todos los días.",
    image_url: "/images/product-0.webp",
    active: true,
    sort_order: 2,
  },
  {
    id: "accesorios",
    name: "Accesorios",
    slug: "accesorios",
    description: "Detalles que acompañan.",
    image_url: "/images/packaging.webp",
    active: true,
    sort_order: 3,
  },
];
const base = {
  neutral_name: "Selección personal",
  short_description: "Un detalle para tu ritual personal.",
  description:
    "Producto de demostración para explorar la experiencia de L’Amour. La fotografía es una ilustración editorial. Su ficha, precio, disponibilidad y plazo son ejemplos; no representan una oferta comercial.",
  compare_at_price: null,
  lead_time_min_days: null,
  lead_time_max_days: null,
  featured: false,
  active: true,
  is_new: false,
  is_demo: true,
  tags: ["ritual", "bienestar"],
  category_ids: [],
  highlights: [
    "Selección con información clara",
    "Entrega y disponibilidad a confirmar",
    "Empaque discreto",
  ],
  notice_text: "",
  notice_tone: "info",
  materials:
    "Ficha de demostración. Materiales por confirmar con el proveedor.",
  dimensions: "Por confirmar con el proveedor.",
  care: "Consultar las instrucciones del fabricante antes de utilizar.",
  usage_note:
    "Uso exclusivo para personas adultas. Seguí siempre las indicaciones del fabricante.",
  return_note:
    "Por higiene, los productos íntimos abiertos o con su sello alterado no admiten devolución, salvo falla o defecto cubierto por la normativa aplicable.",
  variants: [],
  created_at: "2026-09-08T00:00:00Z",
};
export const demoProducts: Product[] = [
  {
    id: "demo-1",
    name: "Huile · aceite de masaje",
    slug: "huile-aceite-masaje",
    sku: "DEMO-001",
    category_id: "parejas",
    price: 149000,
    availability_type: "on_order",
    stock_quantity: 0,
    lead_time_min_days: 12,
    lead_time_max_days: 18,
    featured: true,
  },
  {
    id: "demo-2",
    name: "Nuit · antifaz de seda",
    slug: "nuit-antifaz",
    sku: "DEMO-002",
    category_id: "accesorios",
    price: 119000,
    availability_type: "available",
    stock_quantity: 8,
    featured: true,
    is_new: true,
  },
  {
    id: "demo-3",
    name: "Lueur · vela aromática",
    slug: "lueur-vela",
    sku: "DEMO-003",
    category_id: "personal",
    price: 179000,
    availability_type: "low_stock",
    stock_quantity: 2,
    featured: true,
  },
  {
    id: "demo-4",
    name: "Secret · estuche de satén",
    slug: "secret-estuche",
    sku: "DEMO-004",
    category_id: "accesorios",
    price: 89000,
    availability_type: "available",
    stock_quantity: 12,
  },
  {
    id: "demo-5",
    name: "Élan · masajeador personal",
    slug: "elan-masajeador",
    sku: "DEMO-005",
    category_id: "personal",
    price: 329000,
    availability_type: "on_order",
    stock_quantity: 0,
    lead_time_min_days: 15,
    lead_time_max_days: 22,
    featured: true,
    is_new: true,
  },
  {
    id: "demo-6",
    name: "Douce · limpieza delicada",
    slug: "douce-limpieza",
    sku: "DEMO-006",
    category_id: "cuidado",
    price: 99000,
    availability_type: "sold_out",
    stock_quantity: 0,
  },
  {
    id: "demo-7",
    name: "Ensemble · caja de regalo",
    slug: "ensemble-caja",
    sku: "DEMO-007",
    category_id: "parejas",
    price: 249000,
    availability_type: "on_order",
    stock_quantity: 0,
    lead_time_min_days: 10,
    lead_time_max_days: 16,
    is_new: true,
  },
  {
    id: "demo-8",
    name: "Nuage · paño de cuidado",
    slug: "nuage-pano",
    sku: "DEMO-008",
    category_id: "cuidado",
    price: 69000,
    availability_type: "available",
    stock_quantity: 6,
  },
].map((p, i) => ({
  ...base,
  ...p,
  category_ids: [p.category_id],
  images: [`/images/product-${i}.webp`, "/images/packaging.webp"],
  neutral_name: `Selección ${String(i + 1).padStart(2, "0")}`,
})) as Product[];
export const defaultSettings: Settings = {
  demo: true,
  age_gate: true,
  payments: [
    {
      id: "transfer",
      name: "Transferencia bancaria",
      enabled: false,
      instructions: "",
    },
    { id: "qr", name: "QR / pago manual", enabled: false, instructions: "" },
    {
      id: "cash",
      name: "Efectivo contra entrega",
      enabled: true,
      instructions: "El pago se coordina una vez confirmado el pedido.",
    },
  ],
  delivery: [
    { id: "delivery", name: "Envío a domicilio", enabled: true, price: 25000 },
    { id: "pickup", name: "Retiro coordinado", enabled: true, price: 0 },
  ],
  contact_email: "",
  legal_name: "",
  tax_id: "",
  business_address: "",
  whatsapp: "",
  instagram: "",
  shipping_text:
    "Confirmamos cobertura, costo y plazo antes de preparar tu pedido. Los productos por pedido tienen tiempos individuales y están sujetos a confirmación de disponibilidad. Si combinás productos disponibles y por pedido, coordinaremos la entrega con vos.",
  privacy_text: completePrivacyText,
  terms_text: completeTermsText,
  reservation_text: "",
  banner: "Empaque discreto · Atención personalizada · Paraguay",
  hero_title: "Más que un placer, un espacio para ti.",
  hero_description:
    "Bienestar íntimo, diseño y discreción en una experiencia pensada para acompañarte.",
  hero_image: "/images/brand-woman-flower.webp",
  story_title: "Lo íntimo también es extraordinario.",
  story_description:
    "Creemos en el bienestar que empieza con vos. En elegir sin apuro, descubrir sin prejuicios y encontrar detalles que se sientan propios.",
  story_image: "/images/brand-woman-satin.webp",
  zones: [],
};
